[tool.commitizen]
name = "cz_conventional_commits"

version = "0.2.0"
version_files = [
    "VERSION"
]

tag_format = "$version"

changelog_file = "CHANGELOG.md"
changelog_incremental = true
update_changelog_on_bump = true
major_version_zero = true

bump_message = "chore(release): bump version $current_version â†’ $new_version"

allow_breaking_change = ["refactor"]

change_type_map = {"feat" = "ğŸš€ Features", "fix" = "ğŸ› Bug Fixes", "perf" = "âš¡ Performance Improvements", "docs" = "ğŸ“ Documentation", "style" = "ğŸ’„ Code Style", "refactor" = "â™»ï¸ Code Refactoring", "test" = "âœ… Tests", "build" = "ğŸ‘· Build System", "ci" = "ğŸ’š Continuous Integration", "chore" = "ğŸ”§ Chores", "revert" = "âª Reverts"}